### ISSUE TITLE
Attribution des données carthographiques

### ISSUE THREAD

**Issue by rgrunbla** [GuilhemHnr/trackui#2]
Hello,

Le fond de carte que vous utilisez pour trackui est produit à l'aide de données carthographiques Openstreetmap.

Il faut donc respecter la licence: https://www.openstreetmap.fr/open-data/

En particulier:

>Vous êtes libre de copier et d’adapter nos données, **à condition de créditer OpenStreetMap** et ses contributeurs (avec la mention « © [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright), sous licence ODbL »).

De même, indiquer la provenance des tuiles cartographiques est une bonne idée (sous quelle licence ces tuiles sont elles disponibles ?)

**Comment by GuilhemHnr** [comment]
Reçu, on va modifier le site au plus tôt pour respecter ces licences.
